### ISSUE TITLE
How to distinguish inductive and transductive few-shot methods?

### ISSUE THREAD

**Issue by bighuang624** [yaoyao-liu/few-shot-classification-leaderboard#2]
Thank you for your project. 
I'd like to know how do you distinguish a few-shot learning method from an inductive one or a transductive one? Is there a clear distinction between these two settings in few-shot learning?

**Comment by icoz69** [comment]
hi
generally, the inductive setting the raw setting with no extra data involved, while in the transductive setting, **unlabeled data** (from other query images) can be used to help predictions. so their main difference is while unlabeled extra data are used.

**Comment by bighuang624** [comment]
So the difference lies in whether other query samples are used to predict the current query sample. I got it.
Thank you for your reply.
