### ISSUE TITLE
Suggestion for an addiotional column

### ISSUE THREAD

**Issue by eladmeir** [yaoyao-liu/few-shot-classification-leaderboard#20]
I think that all of us could benefit from a "my own implementation performance" column
i.e. if one tries it out, with any implementation, it is crucial information that can save a lot of time and effort.

I'd limit the addition of entries for this column (section) to an open source code provided with training details (**including data**) that can be trained to achieve similar performance given the same data
But even without the open source, I think that this feature is nice to have

**Comment by yaoyao-liu** [comment]
Thanks for your interest in this project.

This project aims to keep on track with the state-of-the-art (SOTA) for the few-shot classification. So most of the results are from peer-reviewed publications. It is hard to re-implement different methods by myself. And it is also very difficult to check the reliability of other open-source projects. If you are looking for the implementation of different methods, maybe you could check [this project](https://github.com/RL-VIG/LibFewShot).

**Comment by eladmeir** [comment]
Great reference, thanks a lot
