### ISSUE TITLE
The SSFSL results of ICI may be modified

### ISSUE THREAD

**Issue by Yikai-Wang** [yaoyao-liu/few-shot-classification-leaderboard#3]
Hi there,
I am the first author of ICI. Very thanks to add our results in your list. The reported accuracy of SSFSL in your repo uses 80 unlabeled data for each class, which is more than the standard setting and resulting in better performance. This may be unfair for other methods. I recommend to use the results of 30/50 unlabeled data, which is most widely setting used in other SSFSL methods. Please see our [paper](https://arxiv.org/pdf/2003.11853.pdf) for more details. 
Besides, now we have an improved version of ICI with better performance. You may add it in your list. Please note that it is now only a arxiv [preprint](https://arxiv.org/pdf/2007.08461.pdf).

**Comment by yaoyao-liu** [comment]
Thanks for reporting the results.
I've updated the results in our repository.
You may also directly create a pull request to update the scores.
