### ISSUE TITLE
One unreliable result on the leaderboard

### ISSUE THREAD

**Issue by hukkai** [yaoyao-liu/few-shot-classification-leaderboard#7]
Hello, thanks to your great leaderboard! It really helps to know the latest work in FSL! However I found one unreliable from the leaderboard:
> LGM-Net | ICML | 2019 | 6CONV | Inductive

I think this result is unreliable because it has a problematic label leak issue from their codes (https://github.com/likesiwell/LGM-Net/issues/5) and the authors of this paper haven't make any response on this issue. Now that this result ranks No. 1 in the inductive settings. I think it may be misleading to people who are not familiar with the paper and not very fair to other researchers. Before the authors of that paper make any clarifications, could you consider remove this result from the leaderboard? I think it would be great to the FSL community. Thanks!

**Comment by yaoyao-liu** [comment]
Hi @hukkai,

Thanks for your interest in our project.
As I am also working on FSL, I noticed that issue several months ago. However, as I am not 100% sure that the results are unreliable, I still included that paper in the leaderboard as it is already published in ICML. 
If the authors of that paper still fail to update the results or respond to the GitHub issue in the following months, we will remove those results from the leaderboard.

Thanks again for your suggestion.

Best,
Yaoyao

**Comment by hukkai** [comment]
Hi @yaoyao-liu，is there any updates regarding this results? Thanks!

**Comment by yaoyao-liu** [comment]
> Hi @yaoyao-liu，is there any updates regarding this results? Thanks!

I didn't see any updates. I will temporarily remove these results from the leaderboard.
